version: '3.2'

services:
  gateway:
    image: nginx:alpine
    container_name: gateway
    depends_on:
      - plan-ui
      - plan-api
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
  plan-ui:
    image: gunni1/tp-ui:0.3
    container_name: plan-ui
  plan-api:
    image: gunni1/plan-api:1.2.0
    container_name: plan-api
    ports:
      - "8080:8080"
    environment:
      PLAN_DB_URL: mongodb://mongodb:27017
  mongodb:
    image: mongo:3.6
    container_name: plan-db
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
      - ./data/configdb:/data/configdb
